### ISSUE TITLE
关于 +dynamicPropertyClass: 方法

### ISSUE THREAD

**Issue by Xwoder** [JungHsu/PingDynamicSynthesizer#1]
示例程序中，视图控制器的`-viewDidLoad`方法中，存在这么一行代码

```objc
[PingDynamicSynthesizer dynamicPropertyClass:[XXX class]];
```

这行代码的意义是什么，一定要写这行代码么？

**Comment by xuzhongping** [comment]
你好，这句代码调用时，才会真正对传入的class进行property的setter与getter自动合成，如果不调用，其他操作都是不生效的。

**Comment by Xwoder** [comment]
好的，谢谢，知道了。这句话要是可以不写就好了，这样侵入性就更少了。

**Comment by xuzhongping** [comment]
其实是有办法不写的，但是为了可控性，保证类在一定的时间才进行合成，而不是在启动时就合成，让用户自己控制在何时进行合成，也有一定的性能优化考虑。

**Comment by Xwoder** [comment]
恩，有道理。

**Comment by xuzhongping** [comment]
我思考了一下，还是自动更好，运行时的加载并没有多少性能损耗，现在已经不需要再写[PingDynamicSynthesizer dynamicPropertyClass:[XXX class]];这行代码了，只需要遵守协议，谢谢你之前的意见，你可以看一下。

**Comment by Xwoder** [comment]
@JungHsu 恩，使用起来更方便了。很好的项目。
